name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # For databases that use always the same version,
          # it defaults to the env variable fallback defined in the docker-compose file
          - NODE_VERSION: 10.x
            MYSQL_VERSION: 5.7
            MARIADB_VERSION: 10.1
            CASSANDRA_VERSION: 2.1
            POSTGRES_VERSION: 9
            MSSQL_COLLATION: Latin1_General_CI_AS
          - NODE_VERSION: 12.x
            MYSQL_VERSION: 5.7
            MARIADB_VERSION: 10.1
            CASSANDRA_VERSION: 3
            POSTGRES_VERSION: 9
            MSSQL_COLLATION: Latin1_General_CS_AS
          - NODE_VERSION: 14.x
            MYSQL_VERSION: 8
            MARIADB_VERSION: 10.5
            CASSANDRA_VERSION: 3
            POSTGRES_VERSION: 13
            MSSQL_COLLATION: Latin1_General_CI_AS

    steps:
    - uses: actions/checkout@v2

    # ------------------------------
    # -- Setup node dependencies for tests
    # ------------------------------
    - name: Use Node.js ${{ matrix.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.NODE_VERSION }}

    - run: npm ci

    # ----------------------------
    # -- Run code validations
    # ----------------------------
    - run: npm run lint
    - run: npm run format:check

    - run: npm run compile

    # ------------------------------
    # -- Setup infra dependencies for tests
    # ------------------------------
    - name: Setup CI dependencies
      run: docker-compose up ci_setup

    - name: Setup CI schemas
      run: ./scripts/setup-schemas.sh

    # ----------------------------
    # -- Run Tests
    # ----------------------------
    - name: Test
      run: npm run test:coverage
